### ISSUE TITLE
golemapp command returns error

### ISSUE THREAD

**Issue by shail** [golemfactory/homebrew-golem#10]
I'm getting this error when trying to run the golemapp on my computer. I tried to reinstalling, but that didn't seem to help. There seems to be a couple errors: The Failed to import scrypt, "Missing trie node" and the final no such file or directory.

```
golemapp

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /Users/shail/Library/Application Support/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/Users/shail/Library/Application Support/golem/SimpleEnv/minilight.ini'
INFO     [golem.client                       ] Client "", datadir: /Users/shail/Library/Application Support/golem/default
WARN [04-30|14:34:43] No etherbase set and no accounts found as default
INFO [04-30|14:34:43] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [04-30|14:34:43] Allocated cache and file handles         database=/Users/shail/Library/Ethereum/testnet/geth/lightchaindata cache=128 handles=1024
INFO [04-30|14:34:43] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Engine: ethash}"
INFO [04-30|14:34:43] Disk storage enabled for ethash caches   dir=/Users/shail/Library/Ethereum/testnet/geth/ethash count=3
INFO [04-30|14:34:43] Disk storage enabled for ethash DAGs     dir=/Users/shail/.ethash                              count=2
INFO [04-30|14:34:43] Loaded most recent local header          number=68736 hash=67a51e…9ae72a td=7106377167940
INFO [04-30|14:34:43] Starting P2P networking
WARN [04-30|14:34:43] Light client mode is an experimental feature
INFO [04-30|14:34:43] RLPx listener up                         self="enode://5bdcb93c38a06cc595c4d0dbbe4a4612c979aa810ab22088feb939de5cecf067a1b308c5c5ced6eec6d8ae9177c78a1289bf2db23c0fd23ab9eac5813badd74d@[::]:30303?discport=0"
ERROR[04-30|14:34:43] Failed to retrieve current release       err="Missing trie node 6fbee02105e78249479283d8e65459e651f34becad725e59a8810980247c63b3"
INFO [04-30|14:34:43] IPC endpoint opened: /Users/shail/Library/Ethereum/testnet/geth.ipc
INFO [04-30|14:34:43] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.86.1)
WARNING  [golem.docker.manager               ] Docker: pulling image golemfactory/base:1.2
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.2:50963->192.168.64.1:53: read: connection refused
ERROR    [golem.docker.manager               ] Docker: error pulling images: Command '['docker', 'pull', 'golemfactory/base:1.2']' returned non-zero exit status 1
WARNING  [golem.docker.manager               ] Docker: building image golemfactory/base:1.2
INFO [04-30|14:34:44] Block synchronisation started
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /private/var/folders/94/j7280n6x01jg3j2vyzvmzzj00000gn/T/_MEIlCe8M0/apps/core/resources: no such file or directory
Traceback (most recent call last):
  File "/Users/golem/Desktop/golem/golemapp.py", line 105, in <module>
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/golem/Desktop/golem/golemapp.py", line 70, in start
  File "/Users/golem/Desktop/golem/gui/startapp.py", line 134, in start_app
  File "/Users/golem/Desktop/golem/gui/startapp.py", line 73, in start_client
  File "/Users/golem/Desktop/golem/golem/docker/manager.py", line 138, in check_environment
  File "/Users/golem/Desktop/golem/golem/docker/manager.py", line 311, in build_images
  File "/Users/golem/Desktop/golem/golem/docker/manager.py", line 288, in command
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'golemfactory/base', '-f', 'core/resources/images/Dockerfile', '.']' returned non-zero exit status 1
Failed to execute script golemapp
```

**Comment by maaktweluit** [comment]
@shail thanks for the report!

Golem has updated a few times since this error, could you please update and check this again?

The `golemapp` code is in another repo: https://github.com/golemfactory/golem
Could you re-create the issue there if it is still failing?
