### ISSUE TITLE
Willl not launch gui

### ISSUE THREAD

**Issue by rollystone95** [golemfactory/homebrew-golem#11]
When I run golemapp off the terminal, I sync up to the most recent block but no gui runs at all no matter what. I am getting an unusual error 

```WARNING  [golem.appconfig                    ] Can't open file /Users/nicholasreid/Library/Application Support/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/Users/nicholasreid/Library/Application Support/golem/SimpleEnv/minilight.ini'```

as well as this 

```ERROR[05-01|17:20:58] Failed to retrieve current release       err="Missing trie node fa6b3078b3b80d481be946d873d54383b8fab6f77b1ae764a69c8a82d1b0241d"```

and 
```Unhandled Error
Traceback (most recent call last):
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 428, in fireEvent
    
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    
--- <exception caught here> ---
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
    
  File "/Users/golem/Desktop/golem/golem/rpc/router.py", line 64, in _start
    
  File "/Users/golem/Desktop/golem/golem/rpc/router.py", line 69, in _start_node
    
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/crossbar/controller/node.py", line 340, in maybe_generate_key
    
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/crossbar/controller/node.py", line 177, in _machine_id
    
exceptions.TypeError: list indices must be integers, not str```

**Comment by rollystone95** [comment]
Sorry, I'm running the latest macOS Sierra on a  2016 MacBook Pro i7

**Comment by maaktweluit** [comment]
@rollystone95 thanks for the report!

The golem application has a brand new GUI since these errors, could you please update and try again?

The code for the app is in other repositories:
- https://github.com/golemfactory/golem for the `golemapp` ( where your logs are from )
- https://github.com/golemfactory/golem-electron for the brand new GUI

If you still have an issue could you report it in one of those 2 repos?
