### ISSUE TITLE
Can anyone help me with this?

### ISSUE THREAD

**Issue by Leochi91** [golemfactory/homebrew-golem#15]
Now, what should I do? Can't write anything more. Apologies for my ignorance, new to industry.

Last login: Thu Jul 13 21:59:03 on ttys000
MBP-de-Leo:~ leochi$ /Users/leochi/Downloads/golem-0.7.1/golemcli ; exit;
required ciphers set(['aes-128-ctr']) not available in openssl library
use homebrew or macports to install newer openssl
> brew install openssl / > sudo port install openssl
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jet86** [comment]
on macOS you should be using Homebrew to install the alpha, then run the Alpha from your /Applications directly (the same as other applications you install). You shouldn't need to run any commands in terminal other than Homebrew commands to install it.

**Comment by Leochi91** [comment]
Thank you jet86,

Just installed homebrew as below:

Last login: Sat Jul 15 20:25:32 on ttys000
Leos-Macbook:~ leochi$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/bin
/usr/local/etc
/usr/local/lib
==> The following existing directories will have their owner set to leochi:
/usr/local/bin
/usr/local/etc
/usr/local/lib
==> The following existing directories will have their group set to admin:
/usr/local/bin
/usr/local/etc
/usr/local/lib
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/include
/usr/local/opt
/usr/local/sbin
/usr/local/share
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/etc /usr/local/lib
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/lib
==> /usr/bin/sudo /usr/sbin/chown leochi /usr/local/bin /usr/local/etc /usr/local/lib
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/lib
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/include /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/include /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown leochi /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/include /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/include /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/mkdir -p /Users/leochi/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/leochi/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown leochi /Users/leochi/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown leochi /Library/Caches/Homebrew
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress


But Golem still gives me the same command...

Am I doing anything wrong?

**Comment by Leochi91** [comment]
Thank you Jet86, now I'm having this issue:

Last login: Sat Jul 15 20:36:30 on ttys001
/Users/leochi/Downloads/golem-0.7.1/golemapp ; exit;
Leos-Macbook:~ leochi$ /Users/leochi/Downloads/golem-0.7.1/golemapp ; exit;

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /Users/leochi/Library/Application Support/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/Users/leochi/Library/Application Support/golem/SimpleEnv/minilight.ini'
Traceback (most recent call last):
  File "/Users/golem/Desktop/golem/golemapp.py", line 118, in <module>
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/Users/golem/Desktop/golem/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/golem/Desktop/golem/golemapp.py", line 78, in start
  File "/Users/golem/Desktop/golem/gui/startapp.py", line 151, in start_app
  File "/Users/golem/Desktop/golem/gui/startapp.py", line 86, in start_client
  File "/Users/golem/Desktop/golem/golem/client.py", line 155, in __init__
  File "/Users/golem/Desktop/golem/golem/transactions/ethereum/ethereumtransactionsystem.py", line 35, in __init__
  File "/Users/golem/Desktop/golem/golem/ethereum/client.py", line 19, in __init__
  File "/Users/golem/Desktop/golem/golem/ethereum/node.py", line 81, in __init__
OSError: Ethereum client 'geth' not found
Failed to execute script golemapp
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Leochi91** [comment]
I'm having this problem now :/

==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
########                                                                  12.2%
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "golem"
Download failed: https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:341:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:335:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:115:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:84:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
Leos-Macbook:~ leochi$ 911216
-bash: 911216: command not found
Leos-Macbook:~ leochi$ python setup.py develop
python: can't open file 'setup.py': [Errno 2] No such file or directory
Leos-Macbook:~ leochi$ golemapp
-bash: golemapp: command not found
Leos-Macbook:~ leochi$

**Comment by Leochi91** [comment]
Hi Jet,

Thank you very much.

Installed Homebrew, installing Golem now and I believe it's synchronysing the whole blockchain network now.

It's at the block 500,000 right now but quite slow, how long this process usually takes? I just have to leave my computer turned on waiting for this?

Kind regards,

Leo

**Comment by Leochi91** [comment]
INFO [07-19|20:12:34] Imported new block headers               count=1    elapsed=1.778ms   number=563183 hash=80a7d7…eb5c1e ignored=0
INFO [07-19|20:12:49] Imported new block headers               count=1    elapsed=870.623µs number=563184 hash=798315…2838ee ignored=0
INFO [07-19|20:13:04] Imported new block headers               count=1    elapsed=1.317ms   number=563185 hash=2f26e0…b72efb ignored=0
INFO [07-19|20:13:05] Imported new block headers               count=0    elapsed=175.399µs number=563185 hash=2f26e0…b72efb ignored=1
INFO [07-19|20:13:20] Imported new block headers               count=1    elapsed=1.372ms   number=563186 hash=d4a0ca…3dfac9 ignored=0
INFO [07-19|20:13:20] Imported new block headers               count=0    elapsed=295.485µs number=563186 hash=d4a0ca…3dfac9 ignored=1
INFO [07-19|20:13:34] Imported new block headers               count=1    elapsed=1.297ms   number=563187 hash=ad3525…dd8e1a ignored=0
INFO [07-19|20:13:49] Imported new block headers               count=1    elapsed=15.943ms  number=563188 hash=731a59…b1365f ignored=0

**Comment by jet86** [comment]
Correct, leave it running until the GUI appears. How long it takes will depend on your computer, but if it finishes syncing and still doesn't launch then there may be another issue.

**Comment by Leochi91** [comment]
I've closed the terminal, and when I oppened again and wrote the installing command, said it was installed already and I was able to run the Golem App.

But now it says, Golem is having trouble connecting. You may need to check your router ports.

I've tried to read the tutorial, but doesn't make sense

**Comment by Leochi91** [comment]
@jet86 

Also the app is saying I have 1,000 GNT Balance, what's this?

**Comment by jet86** [comment]
@Leochi91 that's 1000 tGNT (testnet GNT) so that you're able to test the application. It's not real GNT or worth anything. Yes you'll need to forward ports 3282, 40102 and 40103 as per https://github.com/golemfactory/golem/wiki/Testing - if you need help with that, it might be best to jump on the [Golem project Slack](http://golemproject.org:3000/) and ask for help in #golem_testers
