### ISSUE TITLE
Error: Failed executing: sudo chown root:wheel

### ISSUE THREAD

**Issue by jpita** [golemfactory/homebrew-golem#18]
I opened this issue on cask's github, you can see all the details there.
https://github.com/caskroom/homebrew-cask/issues/37727

**Comment by jet86** [comment]
Have you attempted `sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve` manually? Have you confirmed that `/usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve` exists?

**Comment by jpita** [comment]
This is the output of the sudo command
```| ~ @ Joses-macbook (josepita) 
| => sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Password:
________________________________________________________________________________
| ~ @ Joses-macbook (josepita) 
| => brew cask install golem
==> Satisfying dependencies
==> Installing Formula dependencies: golem
==> Installing golemfactory/golem/golem
==> Downloading https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz
Already downloaded: /Users/josepita/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> echo docker-machine-driver-xhyve need root owner and uid
==> sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Last 15 lines from /Users/josepita/Library/Logs/Homebrew/golem/02.docker-machine-driver-xhyve:
2017-08-17 08:17:07 +0200

sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve 
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'
```

**Comment by jpita** [comment]
Yes, the file does exist

**Comment by jet86** [comment]
Ah, the answer is in this thread: https://github.com/golemfactory/homebrew-golem/issues/16

**Comment by jpita** [comment]
thanks @jet86 , it worked (commenting the lines).
going to close this.
