### ISSUE TITLE
Failed to import scrypt.

### ISSUE THREAD

**Issue by zdavatz** [golemfactory/homebrew-golem#2]
I am trying this on my latest Mac OS 10.12.4 and I get:
```
:>golemapp

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

WARNING  [golem.appconfig                    ] Can't open file /Users/zdavatz/Library/Application Support/golem/SimpleEnv/minilight.ini: [Errno 2] No such file or directory: '/Users/zdavatz/Library/Application Support/golem/SimpleEnv/minilight.ini'
I0331 08:49:34.628982 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default
I0331 08:49:34.629202 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/zdavatz/Library/Ethereum/testnet/geth/lightchaindata
I0331 08:49:34.633693 ethdb/database.go:176] closed db:/Users/zdavatz/Library/Ethereum/testnet/geth/lightchaindata
I0331 08:49:34.637783 node/node.go:176] instance: Geth/v1.5.9-stable-a07539fb/darwin/go1.8
I0331 08:49:34.637826 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /Users/zdavatz/Library/Ethereum/testnet/geth/lightchaindata
I0331 08:49:34.702233 eth/backend.go:276] Successfully wrote custom genesis block: 41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d
I0331 08:49:34.702729 light/lightchain.go:172] Last header: #0 [41941023…] TD=1048576
I0331 08:49:34.702940 light/lightchain.go:172] Last header: #0 [41941023…] TD=1048576
I0331 08:49:34.703866 p2p/server.go:340] Starting Server
I0331 08:49:34.708391 les/backend.go:191] WARNING: light client mode is an experimental feature
I0331 08:49:34.708737 p2p/server.go:608] Listening on [::]:30303
I0331 08:49:34.710607 node/node.go:341] IPC endpoint opened: /Users/zdavatz/Library/Ethereum/testnet/geth.ipc
I0331 08:49:34.718896 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.0.1)
ERROR    [golem.docker.config_manager        ] Couldn't read CPU affinity: 'Process' object has no attribute 'cpu_affinity'
ERROR    [golem.docker.manager               ]
                ***************************************************************
                Docker is not available, not building images.
                Golem will not be able to compute anything.
                Command 'docker info' returned [Errno 2] No such file or directory
                ***************************************************************

Traceback (most recent call last):
  File "/Users/hawk/work/workspaces/golem-project/golem/golemapp.py", line 93, in <module>
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/hawk/work/workspaces/golem-project/golem/golemapp.py", line 63, in start
  File "/Users/hawk/work/workspaces/golem-project/golem/gui/startapp.py", line 121, in start_app
  File "/Users/hawk/work/workspaces/golem-project/golem/gui/startapp.py", line 69, in start_client
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/docker/manager.py", line 101, in check_environment
EnvironmentError
Failed to execute script golemapp
```

**Comment by zdavatz** [comment]
```Brew install docker``` sloves the problem.
