### ISSUE TITLE
failed to obtain an ip address

### ISSUE THREAD

**Issue by zdavatz** [golemfactory/homebrew-golem#3]
Ok, golem-homebrew seems to run but now I get:

```
I0331 08:54:36.726248 core/headerchain.go:342] imported 2048 headers in 990.014ms. #164032 [ee1015f8… / f96decca…]
I0331 08:54:38.461465 core/headerchain.go:342] imported 2048 headers in    1.530s. #166080 [8d4e9270… / 81b85ece…]
Machine didn't return an IP after 120 seconds, aborting
ERROR    [golem.docker.manager               ] DockerMachine: failed to start the VM: Command '['docker-machine', 'start', 'golem']' returned non-zero exit status 1
Error checking TLS connection: Host is not running
Traceback (most recent call last):
  File "/Users/hawk/work/workspaces/golem-project/golem/golemapp.py", line 93, in <module>
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/hawk/work/workspaces/golem-project/golem/golemapp.py", line 63, in start
  File "/Users/hawk/work/workspaces/golem-project/golem/gui/startapp.py", line 121, in start_app
  File "/Users/hawk/work/workspaces/golem-project/golem/gui/startapp.py", line 69, in start_client
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/docker/manager.py", line 130, in check_environment
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/docker/manager.py", line 364, in _set_docker_machine_env
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/docker/manager.py", line 287, in command
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 219, in check_output
subprocess.CalledProcessError: Command '['docker-machine', 'env', '--shell', 'cmd', 'golem']' returned non-zero exit status 1
Failed to execute script golemapp
```

**Comment by gborowik** [comment]
Please uninstall version 0.3.2 and try 0.4.0. Please write whether it works or not.

**Comment by gborowik** [comment]
Fixed. Run `brew untap ethereum/ethereum`, `brew uninstall ethereum`, `brew tap golemfactory/golem`, `brew install golem`

**Comment by zdavatz** [comment]
ok, I will try this again.
