### ISSUE TITLE
Incompatible Ethereum client

### ISSUE THREAD

**Issue by ericxtang** [golemfactory/homebrew-golem#8]
Installed via brew, and got this when trying to run `golemapp`

```
Traceback (most recent call last):
  File "/Users/hawk/work/workspaces/golem-project/golem/golemapp.py", line 98, in <module>
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/hawk/work/workspaces/golem-project/golem/golemapp.py", line 68, in start
  File "/Users/hawk/work/workspaces/golem-project/golem/gui/startapp.py", line 125, in start_app
  File "/Users/hawk/work/workspaces/golem-project/golem/gui/startapp.py", line 70, in start_client
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/client.py", line 126, in __init__
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/transactions/ethereum/ethereumtransactionsystem.py", line 30, in __init__
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/ethereum/client.py", line 19, in __init__
  File "/Users/hawk/work/workspaces/golem-project/golem/golem/ethereum/node.py", line 75, in __init__
OSError: Incompatible Ethereum client 'geth' version: 1.4.12
Failed to execute script golemapp
```

**Comment by gborowik** [comment]
Due to an incompatibility of recent Xcode and ethereum we have removed ethereum as dependency from golem formula. Please check how to reinstall https://github.com/golemfactory/homebrew-golem
